### ISSUE TITLE
Native Settings

### ISSUE THREAD

**Issue by RaphaelWoude** [capacitor-community/proposals#103]
## Plugin Request

**Name**: Native Settings
**Package**: `@capacitor-community/native-settings`

### Platform(s)

- iOS
- Android

### Existing Solutions

Cordova: https://github.com/guyromb/Cordova-open-native-settings

### Description

This plugin will be able to open native settings screens on iOS and Android.
Currently I am creating a plugin that can be used for capacitor-community. 
https://github.com/RaphaelWoude/capacitor-native-settings

**Comment by RaphaelWoude** [comment]
The plugin has been updated to add the latest iOS functionality.

**Comment by riderx** [comment]
@RaphaelWoude i added your plugin to [awesome-capacitor](https://github.com/riderx/awesome-capacitor) if that is useful please take time to star the repo as well :)

**Comment by ptmkenny** [comment]
@riderx Did you mean "star" the repo?  At a minimum, please proofread your messages before you post 40+ times in these Issues.

**Comment by riderx** [comment]
@ptmkenny thanks i will update all of them

**Comment by riderx** [comment]
@ptmkenny sorry to have been spammy, i didn't think few person will receive many notification...

**Comment by reslear** [comment]
hi @imhoffd please report any news?)

**Comment by RaphaelWoude** [comment]
Plugin is still being maintained. Still very interested to bring this to the capacitor community organization.

**Comment by reslear** [comment]
wait community, maybe you need to prepare everything according to the template capacitor plugin - README.md ?
