### ISSUE TITLE
Background Tasks

### ISSUE THREAD

**Issue by pete-mcwilliams** [capacitor-community/proposals#108]
## Plugin Request

**Name**: Background Task
**Package**: `@capacitor-community/background-task`

### Platform(s)
iOS, Android

### Existing Solutions
https://github.com/robingenz/capacitor-background-task

### Description
Previously an Ionic Capacitor plugin that has been dropped in version 3
Drop in replacement for https://capacitorjs.com/docs/apis/background-task#background-tasks

https://github.com/ionic-team/capacitor/issues/3032

**Comment by Sibi4** [comment]
Does this plugin work when the app is closed/removed from the multitasking bar, or it works only when the app is minimized?

**Comment by pete-mcwilliams** [comment]
The intention is to allow a small task to complete before the application is closed/backgrounded.  It is not intended to work in background.

**Comment by Sibi4** [comment]
I want to send some local Notifications (@capacitor/local-notifications), even after closing the app. That's why I thought of using this plugin. But it cannot be used in my case, right?

**Comment by pete-mcwilliams** [comment]
It was never the intention to run background tasks.  Only allow a short lived process to complete prior to the application closing.

**Comment by Sibi4** [comment]
Ok, thank you!

**Comment by johnborges** [comment]
Looks like its being tracked in this issue too [#3032](https://github.com/ionic-team/capacitor/issues/3032)

**Comment by pete-mcwilliams** [comment]
#3032 is a link from [Ionic's upgrade guide to v3](https://capacitorjs.com/docs/updating/3-0#background-task-permissions-and-photos-plugins-removed)where they have dropped the functionality that allowed small tasks to complete before the app closes, they considered it to be underused and misunderstood.  

It left a few of us high and dry if using the plugin correctly for completing http requests for example.

3032 is referencing a different requirement than the plugin that was removed addressed, and due to the link from the v3 upgrade guide 3032 has become a amalgamation of two things:
1) a feature request for really background tasks (tasks that will run when the application is in the background).
2) a discussion about the missing plugin (tasks that are allowed to complete as the application is going into the background).

[robingenz](https://github.com/robingenz/capacitor-background-task) has ported the ios portion of the old plugin into his own repository and this feature request is an attempt to get that adopted into the community plugins.

**Comment by riderx** [comment]
@pete-mcwilliams  i added your plugin to [awesome-capacitor](https://github.com/riderx/awesome-capacitor) if that is useful please take time to star the repo as well :)

**Comment by pete-mcwilliams** [comment]
@riderx could you reach out to robingenz to let him know, he's the author, I was just trying to get it adopted by as a community plugin.

**Comment by riderx** [comment]
i did for many plugin he did already :) thanks

**Comment by pete-mcwilliams** [comment]
robingenz says
This plugin is now maintained by the Capawesome Organization.
We do not plan to move it to the Capacitor Community Organization.
