### ISSUE TITLE
Google Places API

### ISSUE THREAD

**Issue by Spinnenzunge** [capacitor-community/proposals#111]
Capacitor plugin for Google Places API using the respective platform SDK (iOS, Android, Web) for the best experience, given google places search are cheaper / free when using the native SDK on iOS and Android.

## Plugin Request

**Name**: google-places-api
**Package**: `@capacitor-community/google-places-api`

### Platform(s)

- Android
- iOS
- Web

### Existing Solutions

- None

### Description

The google places api is available as an SDK for Android, iOS and Javascript. It would be great to have a capacitor plugin that wraps them all together in one plugin and provides the common most used features:
- Places search
- Text search
- Autocomplete

**Comment by gugahoi** [comment]
I wonder what benefits this would bring over using something that is "web only"? Would that not suffice for the majority of apps out there?

**Comment by Spinnenzunge** [comment]
I thought that it was cheaper when using the native Android or iOS SDK. But I just checked a bit and I might be wrong. I am not 100% sure tho. If of course the prices do not differ for the javascript and the native SDK then of course this plugin proposal is void. Maybe someone can confirm / deny the pricing difference?

**Comment by willydavid1** [comment]
https://github.com/ionic-team/capacitor-google-maps/issues/111

**Comment by Spinnenzunge** [comment]
I'll close this request in consideration of the new issue of @willydavid1 in the official ionic capacitor plugin
