### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by techster10173** [capacitor-community/proposals#122]
## Plugin Request

**Name**: Calendar
**Package**: `@capacitor-community/calendar`

### Platform(s)
ios
android

### Existing Solutions

`@ionic-enterprise/calendar`
`@ionic-native/calendar` - I have used this one and it works great. All the functionality is strong.

### Description

This plugin would have the same features as the existing alternatives however, this is purely capacitor-based and built by the community

**Comment by jamesyoung1337** [comment]
It would also be nice to have an events or agenda calendar, with drag and drop and resize events that fire to give their new start/end times, kind of like fullcalendar @ fullcalendar.io.

**Comment by eduboxgithub** [comment]
I'm currently using the Cordova plugin for Calendar and it works so far, but it will be awesome so have a full Capacitor version.

**Comment by edy-ap** [comment]
Its already existing one
https://github.com/Fir3st/capacitor-calendar

**Comment by kmkamath** [comment]
Why was this proposal closed as completed? Is there an "official" or "community" capacitor calendar plugin? If so, can we please link the same here.
