### ISSUE TITLE
Sign in with Apple

### ISSUE THREAD

**Issue by Ionitron** [capacitor-community/proposals#14]
## Plugin Request

**Name**: Sign in with Apple
**Package**: `@capacitor-community/apple-sign-in`

### Platform(s)

Android, iOS

### Existing Solutions

https://github.com/pscsrv/cordova-plugin-apple-login
https://github.com/twogate/cordova-plugin-sign-in-with-apple

**Comment by Ionitron** [comment]
Original request: https://github.com/ionic-team/capacitor/issues/2308

**Comment by dwieeb** [comment]
I believe @mlynch is cookin' up something for Apple Sign-in: https://github.com/capacitor-community/apple-sign-in 🎉
