### ISSUE TITLE
Pick Contact

### ISSUE THREAD

**Issue by atrefab** [capacitor-community/proposals#141]
Hi everyone, 
I wonder if it would possible to have a method inside the contact plugin to pick a single contact by using the os native UI as the cordova deprecated plugin did through the method pickContact.

Best regards,

**Comment by calvinckho** [comment]
There is [one](https://github.com/TeamMaestro/capacitor-contact-picker) created for Capacitor 2. I forked it and adapted it for Capacitor 3: https://github.com/calvinckho/capacitor-contact-picker/tree/release
