### ISSUE TITLE
Set version numbers for new release

### ISSUE THREAD

**Issue by pbowyer** [capacitor-community/proposals#157]
## Plugin Request

**Name**: make-release
**Package**: `@capacitor-community/make-release`

### Platform(s)

- Android
- iOS
- Web & Electron?

### Existing Solutions

I haven't found any, but it's a question that comes up e.g.
https://github.com/ionic-team/capacitor/discussions/3164
https://stackoverflow.com/questions/63394363/how-can-i-set-the-android-build-version-in-an-ionic-app
https://stackoverflow.com/a/59072775/119750

### Description

When making a new release, it would be wonderful to have a command to set the version number (and possibly build number) consistently across Android, iOS and other outputs. Currently this must be done manually, and it's a pain to do.

Something like the [`np`](https://github.com/sindresorhus/np) command for NPM would be super-helpful.

I'm aware some people set their version numbers via their CI server and I'm open to alternative approaches. Not having CI running fo this small app, something that can be run on my development machine is preferred.

**Comment by robingenz** [comment]
Hi @pbowyer,
Have you looked at [capacitor-configure](https://github.com/ionic-team/capacitor-configure) yet? It should be able to do just that.

**Comment by pbowyer** [comment]
Hi @robingenz, I wasn't aware of `capacitor-configure`. With a bit of scripting it looks like it can do what I need. Awesome!

**Comment by ptmkenny** [comment]
You can also use [Fastlane](https://docs.fastlane.tools/), which is open source and free of charge.

Fastlane can increment version numbers (either manually or automatically in a CI/CD setup) and do other useful things like automate screenshot capture, deployment to beta testing services, and so on.  I have it working with an Ionic React app.

**Comment by jcesarmobile** [comment]
this can be achieved with [trapeze](https://trapeze.dev/docs/) (previously known as capacitor-configure.
