### ISSUE TITLE
Capacitor File Opener

### ISSUE THREAD

**Issue by ateeq26** [capacitor-community/proposals#164]
**Name**: FileOpener
**Package**: `@capacitor-community/file-opener`

### Platform(s)

android
ios

### Existing Solutions

cordova-plugin-file-opener2

### Description
The plugin should be able to open a file given the mimeType and the file uri
The cordova-plugin-file-opener2 is not working in capacitorV3

**Comment by ryaa** [comment]
Here is initial release of the required plugin https://github.com/capacitor-community/file-opener (still not published yet). Please note right now this version of the plugin is for Android platform only .

**Comment by rajild** [comment]
Looking forward to use this when ready to iOS and Android both.

**Comment by ryaa** [comment]
> Looking forward to use this when ready to iOS and Android both.

It is already almost complete and i'm planning to add iOS support beginning of the next week.

**Comment by ryaa** [comment]
The support for iOS has been added. Can anyone install from the github using the below command to give it a try
`npm install capacitor-community/file-opener#chore/latest-version-with-dist-directory`

I still don't have permission to publish the package yet and waiting for Ionic team to approve it.

**Comment by ryaa** [comment]
The capacitor file opener plugin has been published - see https://www.npmjs.com/package/@capacitor-community/file-opener

My assumption is that this ticket can be closed :)
