### ISSUE TITLE
Listen to hardware volume button clicks

### ISSUE THREAD

**Issue by thiagobrez** [capacitor-community/proposals#165]
## Plugin Request

**Name**: capacitor-volume-buttons
**Package**: `@capacitor-community/volume-buttons`

### Platform(s)

iOS and Android

### Existing Solutions

https://github.com/thiagobrez/capacitor-volume-buttons

### Description

There was no solution to listen to hardware volume button presses that contemplated both iOS and Android. So I have created the above package and would like to include it in the Capacitor Community repo!

**Comment by riderx** [comment]
@thiagobrez Awesome! You are welcome to add it to https://github.com/riderx/awesome-capacitor your work deserve to be more knew!

**Comment by ryaa** [comment]
@thiagobrez can you please add a license to your original repo? see details here https://github.com/thiagobrez/capacitor-volume-buttons/issues/5. thank you

**Comment by ryaa** [comment]
The capacitor volume-buttons plugin has been published - see https://github.com/capacitor-community/volume-buttons

My assumption is that this ticket can be closed

**Comment by thiagobrez** [comment]
Awesome, great work! Closing this one
