### ISSUE TITLE
Background Geolocation

### ISSUE THREAD

**Issue by josuelmm** [capacitor-community/proposals#174]
**The best plugins is**
https://www.npmjs.com/package/cordova-background-geolocation-plugin

Use it with
@awesome-cordova-plugins/background-geolocation

```
$ npm install cordova-background-geolocation-plugin
$ npm install @awesome-cordova-plugins/background-geolocation 
$ ionic cap sync
```

**Comment by jcesarmobile** [comment]
https://github.com/capacitor-community/background-geolocation already exists

**Comment by josuelmm** [comment]
That capacitor plugin is not complete at all, as is the one I am commenting on.

**Comment by jcesarmobile** [comment]
You can request features on the plugin repository
