### ISSUE TITLE
handle unmaintained capacitor plugins like firebase fcm

### ISSUE THREAD

**Issue by daniel-zero** [capacitor-community/proposals#179]
I'm not sure if this is the right place to start this discussion but there is currently one major issue with capacitor plugins _maintained_ by community members. There are multiple plugins heavily used by the community like the firebase plugins that are unmaintained since months or even years. With the latest capacitor v4 upgrade it is even more obvious.

I don't know the answer to resolve this issue but it should be resolve so developers can profit not only from the latest capacitor updates but also from maintained and up to date plugins.

**Comment by jcesarmobile** [comment]
fcm plugin now supports capacitor 4, was updated a few months back.

Sadly, community maintainers are volunteers and work whenever they can, we can't force them to update. But if a plugin is unmaintained, anybody can step up and offer themselves as new maintainers of unmaintained plugins, there are a few maintainers with owner permission so they can add new people.
