### ISSUE TITLE
Speech Recognition

### ISSUE THREAD

**Issue by Ionitron** [capacitor-community/proposals#18]
## Plugin Request

**Name**: Speech Recognition
**Package**: `@capacitor-community/speech-recognition`

### Platform(s)

Android, iOS

### Existing Solutions

https://github.com/pbakondy/cordova-plugin-speechrecognition

**Comment by Ionitron** [comment]
Original request: https://github.com/ionic-team/capacitor/issues/1729

**Comment by priyankpat** [comment]
https://github.com/capacitor-community/speech-recognition now supports Android/iOS. Web version is also being worked on. Please give it a try and open issues if you find a problem. PRs are also welcome :smile
