### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by Ionitron** [capacitor-community/proposals#19]
## Plugin Request

**Name**: Media
**Package**: `@capacitor-community/media`

### Platform(s)

Android, iOS

### Existing Solutions

https://github.com/apache/cordova-plugin-media-capture/
https://github.com/edimuj/cordova-plugin-audioinput

### Description

- Audio/Image/Video capturing
- Album management
- [`getUserMedia`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) doesn't work on iOS, so we need a way to capture audio/video in Capacitor.

**Comment by Ionitron** [comment]
Original request: https://github.com/ionic-team/capacitor/issues/1669

**Comment by dwieeb** [comment]
https://github.com/capacitor-community/media now exists thanks to @stewwan 

Nothing is published yet, the repo was just imported.

**Comment by D-Marc1** [comment]
It would be best to have a unified media plugin for getting the camera, video camera and audio. It should also be able to get both the photo and video library. Right now, the camera plugin can strictly get the camera and photo library. For iOS, you can actually trigger the camera with an html `<input>`, though you can't do so programmatically.

**Comment by lishid** [comment]
According to <https://bugs.webkit.org/show_bug.cgi?id=220184> (Landed in 2021-01-07) `getUserMedia` will be available soon, likely in iOS 14.5.

**Comment by anonmate** [comment]
Is there any update on this? Apple has said it's fixed so is the plugin necessary? https://bugs.webkit.org/show_bug.cgi?id=220184

**Comment by lishid** [comment]
> Is there any update on this? Apple has said it's fixed so is the plugin necessary? https://bugs.webkit.org/show_bug.cgi?id=220184

I've been able to record audio with the new API without needing a plugin since iOS 14.5.

**Comment by Ken-vdE** [comment]
@lishid Could you give an example of how you achieved this?
