### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by Ionitron** [capacitor-community/proposals#20]
## Plugin Request

**Name**: Google Maps
**Package**: `@capacitor-community/google-maps`

### Platform(s)

Android, iOS

### Existing Solutions

https://github.com/mapsplugin/cordova-plugin-googlemaps, but doesn't work in Capacitor iOS yet (see https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2781)

An alternative would be using the web SDK as shown in [this blog by Josh Morony](https://www.joshmorony.com/using-google-maps-and-geolocation-in-ionic-with-capacitor/). Using the native SDK has several benefits, however: fewer requests, offline map caching, ability to work offline, etc.

### Description

A plugin for using the native Google Maps SDK.

**Comment by Ionitron** [comment]
Original request: https://github.com/ionic-team/capacitor/issues/629

**Comment by hemangsk** [comment]
https://github.com/hemangsk/capacitor-googlemaps-native has some basic google maps working for android and ios (using native SDK) and can be used in Capacitor apps. Some features like street view, drawings are not there yet and its currently under development for this reason, please feel free to join forces & collaborate! :)

**Comment by wf9a5m75** [comment]
@hemangsk  Thank you for the information. This is just my curiosity. Is the `capacitor-googlemaps-native` able to display a side bar over the map (like this image)?

As you can see, I expect touch the menu items over the map.

![capture (1)](https://user-images.githubusercontent.com/167831/86501352-014a4f00-bd4d-11ea-986f-ba6f4cf0645b.png)

By the way, I have been working on [this project](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2781) recently.
It means `cordova-plugin-googlemaps` will support `Capacitor iOS` officially.

**Comment by imhoffd** [comment]
Thanks @wf9a5m75, I've updated the proposal with the current status of your plugin.

**Comment by tototares** [comment]
@wf9a5m75 Will support your plugin only IOS? What's about Android?

**Comment by wf9a5m75** [comment]
Cordova-plugin-googlemaps with @ionic-native/google-maps works on Capacitor Android currently

**Comment by tototares** [comment]
@wf9a5m75 that's true but for that you need ionic-native. Would be great to have a plugin for iOS and Android where you doesn't need something else but capacitor.

**Comment by wf9a5m75** [comment]
In the future, probably yes, but step by step

**Comment by hemangsk** [comment]
@wf9a5m75 I'm quite certain https://github.com/hemangsk/capacitor-googlemaps-native could do that, 

> This is just my curiosity. Is the capacitor-googlemaps-native able to display a side bar over the map (like this image)?

but if you're not being able to get that look which you are going for, let me know in the [issues](https://github.com/hemangsk/capacitor-googlemaps-native)  here and I'll try to help you with a workaround :)

**Comment by wf9a5m75** [comment]
Thanks, but so far so good. Capacitor iOS supporting project is on the way. I will ask your help when I need.

**Comment by THEDOWNCOUNTRY** [comment]
@wf9a5m75 when will the plugin be available for iOS?

**Comment by DwieDima** [comment]
@THEDOWNCOUNTRY project started on 24. june and estimated time was 3 months. It got extended for another month, so release should hopefully be on 24. october.

**Comment by THEDOWNCOUNTRY** [comment]
@DwieDima hopefully because this plugin is awesome. At the moment, to use it for iOS, I only have CORDOVA plugins on my project, so I don't have to rewrite code for android, and that's frustrating when some plugins like firebase analytics don't work for android.

**Comment by SalahAdDin** [comment]
@DwieDima how was it?

**Comment by DwieDima** [comment]
> @DwieDima how was it?

@SalahAdDin no ETA
you can track current state of development here:
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2781

**Comment by SalahAdDin** [comment]
@hemangsk is it still active?

**Comment by selected-pixel-jameson** [comment]
Where is the Ionic / Capacitor team in all of this? It seems like core functionality to have the maps SDK in any kind of mobile framework. Its pretty much non-existent for iOS. The Cordova plugin doesn’t work for iOS and the development progress is at a standstill. Let’s get this moving forward.  @capacitor-community-bot @Ionitron

**Comment by wf9a5m75** [comment]
@selected-pixel-jameson Why don't you try to create a new plugin by yourself?

**Comment by selected-pixel-jameson** [comment]
@wf9a5m75 I'm at this point. However, it would make a lot more sense to have three people working on the development of one capacitor native maps plugin  vs three separate ones that are partially done. I'll probably just reach out to @hemangsk to see if they are open to pull requests.

**Comment by tototares** [comment]
> @wf9a5m75 I'm at this point. However, it would make a lot more sense to have three people working on the development of one capacitor native maps plugin vs three separate ones that are partially done. I'll probably just reach out to @hemangsk to see if they are open to pull requests.

yeah I agree! He is answering to pull requests very fast and there is no other capacitor project for native maps support for ios and android.

**Comment by wf9a5m75** [comment]
Ok, no problem. Existing choice is a good option. I'm developing a new version, but a lots of task. But certainly I'm not "**standstill**"

**Comment by AE1NS** [comment]
@wf9a5m75 will it be open source later? Maybe you could set your repository to public with the current state to let other skilled developers contribute and support you with completing it, like @selected-pixel-jameson mentioned. We appreciate all your work @wf9a5m75 and @hemangsk!

**Comment by wf9a5m75** [comment]
> will be open source?

Tentatively, yes. But many people did only request instead of contribution. I'm considering.

**Comment by selected-pixel-jameson** [comment]
Just an updated to the @capacitor-community-bot on where Capacitor is on the progress of having native maps implementation. 

@hemangsk and @wf9a5m75 are both working away to try and get releases out, but obviously this is quite an undertaking. 

@wf9a5m75 has a private repo he has shared with individuals who have donated to the project. Progress is being made and updates are sent out every few weeks or so. 

@hemangsk has a public version that receives updates pretty often. They seem to respond quickly to issues posted as well. There are two items with this repo that I would consider preventing it from a fully usable solution. 
1. The map cannot be used inline. Right now they are working through figuring this out. 
2. Info boxes are not yet implemented. 

With all this said I want to thank @hemangsk and @wf9a5m75 for their work. Hopefully we will have two viable production options within the next month or so.

**Comment by wf9a5m75** [comment]
@selected-pixel-jameson I understand your frustration. I apologize my work progress is super slow. I'm very hard to find the working time of the maps plugin at this moment.

**Comment by riderx** [comment]
@hemangsk  add your plugin to [awesome-capacitor](https://github.com/riderx/awesome-capacitor) if that is useful please take time to star the repo as well :)

**Comment by jcesarmobile** [comment]
there is @capacitor-community/google-maps and @capacitor/google-maps plugins available, closing the proposal
