### ISSUE TITLE
Local IP Address

### ISSUE THREAD

**Issue by AmirHmZz** [capacitor-community/proposals#206]
## Plugin Request

**Name**: Local IP Address
**Package**: `@capacitor-community/local-ip-address`

### Platform(s)
Android
IOS

### Existing Solutions
There's no solution yet for the purpose. 

### Description
This plugin can be used to get local ip address of device in connected wifi network. This can be useful for finding IOT devices IP addresses on local network in order to connect to them.

**Comment by shiv19** [comment]
@AmirHmZz 
This is possible now:
https://capawesome.io/plugins/wifi/

**Comment by robingenz** [comment]
This is now possible using the [Capacitor Wifi](https://capawesome.io/plugins/wifi/) plugin.

**Comment by AmirHmZz** [comment]
@robingenz Thank you!
