### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by Ionitron** [capacitor-community/proposals#21]
## Plugin Request

**Name**: Firebase
**Package**: `@capacitor-community/firebase`

### Platform(s)

Android, iOS

### Existing Solutions

https://github.com/stewwan/capacitor-analytics for Firebase Analytics

### Description

Capacitor plugin for Firebase features such as Analytics, RemoteConfig, Auth, etc.

**Comment by Ionitron** [comment]
Original request: https://github.com/ionic-team/capacitor/issues/383

**Comment by dwieeb** [comment]
@priyankpat Would it make sense to combine the Firebase plugins (https://github.com/capacitor-community/firebase-analytics and https://github.com/capacitor-community/firebase-crashlytics) into one plugin?

**Comment by imhoffd** [comment]
The Capacitor community now offers a variety of plugins for Firebase: https://github.com/capacitor-community?q=firebase&type=&language=

**Comment by priyankpat** [comment]
@dwieeb  yes, we can combine them. I have other functionality that I can add for firebase regarding ML.

**Comment by imhoffd** [comment]
I actually changed my mind. I like that they're split up. We're doing the same thing with Accessibility: ScreenReader, TextZoom, etc.

**Comment by vimtor** [comment]
I think them being split up mirrors how Firebase web SDK work.

The service I'm missing most is the `firebase-auth`. Right now I'm finding problems for creating native authentication with providers like Google using Ionic + Capacitor.

**Comment by vimtor** [comment]
> I actually changed my mind. I like that they're split up. We're doing the same thing with Accessibility: ScreenReader, TextZoom, etc.

Maybe a core `firebase` plugin that does the main configuration, so then you can opt-in importing the different plugins.

**Comment by somq** [comment]
Sorry to comment on a closed issue but I did not understand why it was closed.
The Capacitor plugins listed above does not cover the full scope of the Firebase API.

What about this one https://github.com/dpa99c/cordova-plugin-firebasex then?
