### ISSUE TITLE
Bluetooth LE

### ISSUE THREAD

**Issue by Ionitron** [capacitor-community/proposals#23]
## Plugin Request

**Name**: Bluetooth LE
**Package**: `@capacitor-community/bluetooth-le`

### Platform(s)

Android, iOS

### Description

Add a plugin with an API for bluetooth low energy.

**Comment by Ionitron** [comment]
Original request: https://github.com/ionic-team/capacitor/issues/1601

**Comment by TimSet0815** [comment]
I would love to have that!

**Comment by conde2** [comment]
That would be awesome!

**Comment by ASHBAW** [comment]
Please implement this.

**Comment by phi1618033** [comment]
Very much needed

**Comment by toniengelhardt** [comment]
Totally need that to play with Arduino

**Comment by RichardZandi** [comment]
Please implement this.

**Comment by tellybrown** [comment]
I have been using @ionic-native/ble/ngx and it works pretty well.  Would be nice to see "Capacitor" specific

**Comment by pwespi** [comment]
I have been working on a Capacitor plugin for Bluetooth Low Energy that supports the web, iOS and Android.

* https://github.com/pwespi/capacitor-bluetooth-le

It's not yet published on npm. I wanted to see if there is interest to add it to the capacitor community directly. What does the process look like to add a new plugin to the capacitor community?

**Comment by dotNetkow** [comment]
@pwespi Getting in touch with you :)

**Comment by imhoffd** [comment]
Hey everyone! @pwespi's implementation has been accepted: https://github.com/capacitor-community/bluetooth-le

Please give it a try 😁
