### ISSUE TITLE
Camera Preview

### ISSUE THREAD

**Issue by dwieeb** [capacitor-community/proposals#31]
## Plugin Request

**Name**: Camera Preview
**Package**: `@capacitor-community/camera-preview`

### Platform(s)

- Android
- iOS
- Web

### Existing Solutions

- https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview (incompatible, see https://github.com/ionic-team/capacitor/issues/1732)
- https://github.com/arielhernandezmusa/capacitor-camera-preview

**Comment by dwieeb** [comment]
@arielhernandezmusa FYI

**Comment by arielhernandezmusa** [comment]
@dwieeb I just transfer https://github.com/arielhernandezmusa/capacitor-camera-preview to capacitor-community

**Comment by dwieeb** [comment]
🎉
