### ISSUE TITLE
iOS 14 IDFA App Tracking

### ISSUE THREAD

**Issue by migtam628** [capacitor-community/proposals#42]
## Plugin Request

**Name**: iOS-IDFA-App-Tracking 
**Package**: `@capacitor-community/ios-idfa-tracking`

### Platform(s)
- [x] iOS

### Existing Solutions

https://github.com/migtam628/capacitor-ios-app-tracking

### Description

My plugin is used to request user authorization to access app-related data for tracking the user or the device.

It implements AppTrackingTransparency for iOS 14.

**Comment by riderx** [comment]
@migtam628 i added your plugin to [awesome-capacitor](https://github.com/riderx/awesome-capacitor) if that is useful please take time to star the repo as well :)

**Comment by migtam628** [comment]
@riderx thank you very much. i appreciate it.
