### ISSUE TITLE
Insomnia

### ISSUE THREAD

**Issue by kevinboosten** [capacitor-community/proposals#49]
## Plugin Request

**Name**: insomnia
**Package**: `@capacitor-community/insomnia`

### Platform(s)

- iOS
- Android

### Existing Solutions

- https://ionicframework.com/docs/native/insomnia
The original cordova plugin with a ionic-native wrapper written by Eddy Verbruggen. 
- https://github.com/Boosten/capacitor-keep-awake
Simple Capacitor version of the Insomnia plugin. 

### Description

Prevent the screen of the mobile device from falling asleep. 
- On iOS by using the [idle timer](https://developer.apple.com/documentation/uikit/uiapplication/1623070-isidletimerdisabled)
- On Android by using [FLAG_KEEP_SCREEN_ON](https://developer.android.com/training/scheduling/wakelock#screen)

**Comment by imhoffd** [comment]
https://github.com/capacitor-community/keep-awake 😁
