### ISSUE TITLE
wechat plug in

### ISSUE THREAD

**Issue by hqylss111** [capacitor-community/proposals#57]
WeChat plugin in ionic 5.0 

The use of technology is React Is there any solution to the WeChat plugin that doesn't seem to be compatible with the official website？
Your reply is urgently needed

**Comment by imhoffd** [comment]
I can't tell if this is a proposal for a new plugin or a support request. Either way, I'm closing it because the proposal template was not used. If you want support use the [Capacitor discussions](https://github.com/ionic-team/capacitor/discussions).
