### ISSUE TITLE
Barcode Scanner

### ISSUE THREAD

**Issue by Ionitron** [capacitor-community/proposals#6]
## Plugin Request

**Name**: Barcode Scanner
**Package**: `@capacitor-community/barcode-scanner`

### Platform(s)

Android, iOS

### Existing Solutions

https://github.com/phonegap/phonegap-plugin-barcodescanner
https://www.npmjs.com/package/@johnbraum/capacitor-qrscanner

**Comment by Ionitron** [comment]
Original request: https://github.com/ionic-team/capacitor/issues/3114

**Comment by johnbraum** [comment]
Hey guys! I already did this for QR Codes, should also work for other type of codes.
https://www.npmjs.com/package/@johnbraum/capacitor-qrscanner

**Comment by nprail** [comment]
Web support with PWA Elements would be pretty awesome as well!

**Comment by johnbraum** [comment]
@nprail if you want you can add this. I thought about this, too.

**Comment by imhoffd** [comment]
Closed in favor of https://github.com/capacitor-community/proposals/issues/53
