### ISSUE TITLE
App Version

### ISSUE THREAD

**Issue by basvdijk** [capacitor-community/proposals#65]
## Plugin Request

**Name**: AppVersion
**Package**: `@capacitor-community/app-version`

### Platform(s)

Android, iOS (web would be of no use since this is the version of the server)

### Existing Solutions

https://github.com/whiteoctober/cordova-plugin-app-version

### Description

The functionality of this plugin is quite simple: it just returns the version of the app.

This could be a string e.g. `1.2.49` or a JSON format with [semver](https://semver.org/) taking into account.:
```
{
 major: 1,
 minor: 2,
 patch: 49,
 value: '1.2.49'
}
```

The JSON format could be useful to create upgrade warnings. So you can say things like: 'if minor < 2' then show upgrade message etc.

## Use cases
- Create user messages depending on version e.g. upgrade warnings
- Helps support desk because they can ask the user which version they are using. We use this a lot in communication with our [app](https://drammer.com) users.

## Nice to haves
The original Cordova app supports some more meta data about the app like:
- app name - e.g. "My todo app"
- package name - e.g. "com.todo.app
- version code - e.g. "build A v2"

From https://github.com/whiteoctober/cordova-plugin-app-version

**Comment by imhoffd** [comment]
The version number and code are currently available with the Device plugin: https://capacitorjs.com/docs/apis/device

However, it may be moving to the App plugin for Capacitor 3. See https://github.com/ionic-team/capacitor-plugins/issues/46

App info like this would make sense as part of the App plugin. I made an issue to track this for Capacitor 3: https://github.com/ionic-team/capacitor/issues/3578

**Comment by basvdijk** [comment]
@dwieeb Thanks for clarifying. I would indeed opt to move it to the app plugin. imho device should be about the device itself.
