### ISSUE TITLE
Native Date Picker

### ISSUE THREAD

**Issue by Ionitron** [capacitor-community/proposals#7]
## Plugin Request

**Name**: Native Date Picker
**Package**: `@capacitor-community/date-picker`

### Platform(s)

Android, iOS, web

### Existing Solutions

https://github.com/triniwiz/capacitor-datepicker
https://github.com/stewwan/capacitor-datepick

**Comment by Ionitron** [comment]
Original request: https://github.com/ionic-team/capacitor/issues/1231

**Comment by dwieeb** [comment]
@stewwan It looks like you transferred your plugin: https://github.com/capacitor-community/capacitor-datepick 🎉 

For consistency, what are your thoughts on renaming the repo to `capacitor-community/date-picker`? The npm package would be `@capacitor-community/date-picker`.

**Comment by stewwan** [comment]
yo @dwieeb yeah I've transferred a bunch.. I didn't rename them because I don't have proper permissions. You can go ahead and rename it all
