### ISSUE TITLE
Screen Brightness

### ISSUE THREAD

**Issue by xzilja** [capacitor-community/proposals#77]
## Plugin Request

**Name**: brightness
**Package**: `@capacitor-community/brightness`

### Platform(s)

iOS and Android

### Existing Solutions

I was able to implement simple one for iOS, not sure if it's the correct way to achieve this however (that `Dispatch.main` code).

```swift
import Capacitor

@objc(Brightness)
public class Brightness: CAPPlugin {
  @objc func get(_ call: CAPPluginCall) {
    call.success([
        "brightness": UIScreen.main.brightness
    ])
  }
    
  @objc func set(_ call: CAPPluginCall) {
    let brightness = call.getFloat("brightness", 1.0)
    DispatchQueue.main.async {
      UIScreen.main.brightness = CGFloat(brightness!)
      call.success()
    }
  }
}
```

### Description

Allow developers to get and set screen brightness

**Comment by robingenz** [comment]
There is a plugin now: https://github.com/capacitor-community/screen-brightness
