### ISSUE TITLE
Native SafeArea

### ISSUE THREAD

**Issue by xzilja** [capacitor-community/proposals#78]
## Plugin Request

**Name**: safe-area
**Package**: `@capacitor-community/safe-area`

### Platform(s)

iOS, Android

### Existing Solutions

I believe recommended way it to use `viewport-fit=cover` alongside css variables like `safe-area-inset-top`. I personally found this very inconsistent in different browsers / os's and there is just not enough info to make decisions on some android screens with camera cut outs.

I'm currently using my own simple implementation on iOS side of things for this, it's not complete

```swift
import Capacitor

@objc(SafeArea)
public class SafeArea: CAPPlugin {
  @objc func get(_ call: CAPPluginCall) {
    DispatchQueue.main.async {
        let insets = self.bridge.getWebView()?.safeAreaInsets
        call.success([
            "top": insets?.top ?? 0,
            "bottom": insets?.bottom ?? 0,
            "left": insets?.left ?? 0,
            "right": insets?.right ?? 0
        ])
    }
  }
}
```

### Description

We should expose native plugin that allows to get accurate data for things like notches, software buttons, camera cut-outs etc... and allows to subscribe to these values, for cases where phone rotation changes.

**Comment by PolymorphiK** [comment]
@IljaDaderko Damn I overlooked this proposal lmao, that's what happens when you don't sleep...rip.

I actually have a solution for Android/iOS, if you got one for iOS you wanna collab and fuse Vegeto style on this? I did not solve the software buttons (i didn't really think about it).

[Proposal](https://github.com/capacitor-community/proposals/issues/92)

**Comment by xzilja** [comment]
@PolymorphiK nice! I mean code I have above is pretty much all that is needed for iOS, feel free to use it if you want 👍 I haven't looked into android yet, but it looks like you have that sorted?

If you create a plugin repo, feel free to ping me here and I will add iOS stuff in.

**Comment by imhoffd** [comment]
I'll close this in favor of the new proposal: https://github.com/capacitor-community/proposals/issues/92

@PolymorphiK @IljaDaderko Please join the [Capacitor Contributors slack](https://getcapacitor.herokuapp.com/) and I can help you get set up in the github org. 😁
