### ISSUE TITLE
Screen Orientation

### ISSUE THREAD

**Issue by Ionitron** [capacitor-community/proposals#8]
## Plugin Request

**Name**: Screen Orientation
**Package**: `@capacitor-community/screen-orientation`

### Platform(s)

Android, iOS

### Existing Solutions

https://github.com/apache/cordova-plugin-screen-orientation
https://github.com/hinddeep/capacitor-screen-orientation

### Description
Ability to get, set, lock, unlock, and receive updates about screen orientation.

**Comment by Ionitron** [comment]
Original request: https://github.com/ionic-team/capacitor/issues/838

**Comment by imhoffd** [comment]
@hinddeep Feel free to leave a comment about your plugin. I added a link to it in the original issue.

**Comment by hinddeep** [comment]
I have ported the existing Cordova Screen Orientation plugin to Capacitor. The iOS portion of the plugin has been written in Swift as opposed to super difficult Objective-C in the case of its Cordova brethren. This makes it super easy to edit if needed. The plugin supports Android, iOS and Web/PWA. Supported functions:

Get the current screen orientation
Lock the screen to the specified orientation
Unlock screen orientation
Listen to screen orientation changes - and then perform any necessary action(s)
Rotate the screen to the specified orientation without locking (iOS only)

**Comment by muuvmuuv** [comment]
@hinddeep can you publish it?

**Comment by riderx** [comment]
@muuvmuuv it's publish, but it look difficult to install for now : https://github.com/hinddeep/capacitor-screen-orientation

**Comment by Pynka** [comment]
Found another one: https://github.com/robingenz/capacitor-screen-orientation

**Comment by riderx** [comment]
@Pynka the one you found look better !

**Comment by muuvmuuv** [comment]
Thanks @Pynka. Seems that the one you posted is for Cap3 and the other one only for Cap2! Cool.

**Comment by riderx** [comment]
@Pynka  I added your plugin to [awesome-capacitor](https://github.com/riderx/awesome-capacitor) if that is useful please take time to star the repo :)

**Comment by jcesarmobile** [comment]
@capacitor/screen-orientation now exists, so there is no need for a community plugin

**Comment by muuvmuuv** [comment]
Can you share the doc link? Couldn't find anything in docs, npm, GH releases or tags.
