### ISSUE TITLE
Changing App Icon

### ISSUE THREAD

**Issue by johnborges** [capacitor-community/proposals#84]
## Plugin Request

**Name**: app-icon
**Package**: `@capacitor-community/app-icon`

### Platform(s)
iOS

### Description
In iOS 10.3, Apple launched a cool function so developers can programmatically change the app icon. This plugin would interface with those APIs to make that feature available to Capacitor apps.

[Example](https://github.com/johnborges/app-icon)

**Comment by imhoffd** [comment]
https://github.com/capacitor-community/app-icon 🎉

**Comment by alexcroox** [comment]
Sorry to ask here but the linked repo doesn't have issues turned on. Could we re-open this proposal for Android support? Currently the community app-icon only supports iOS.

Existing Android references: https://github.com/myinnos/AppIconNameChanger

Also there is no indication if the current app-icon plugin supports Capacitor 3, the README syntax uses Cap 2.

**Comment by johnborges** [comment]
@alexcroox Issues should now be active. There is an active branch with work being done to support Capacitor v3. Adding Android support would be good! Feel free to open an issue so it can get tracked.
