### ISSUE TITLE
Privacy Screen

### ISSUE THREAD

**Issue by robingenz** [capacitor-community/proposals#85]
## Plugin Request

**Name**: Privacy Screen
**Package**: `@capacitor-community/privacy-screen`

### Platform(s)

Android, iOS

### Existing Solutions

https://github.com/robingenz/capacitor-privacy-screen

### Description

Capacitor plugin that protects your app from displaying a screenshot in Recents screen/App Switcher.

**Comment by imhoffd** [comment]
Plugin looks good! Would you be able to join the [Capacitor Contributor slack](https://getcapacitor.herokuapp.com/)? I can help get you started in the Capacitor Community.

**Comment by robingenz** [comment]
Thank you. Yes, I will join today after work.

**Comment by imhoffd** [comment]
https://github.com/capacitor-community/privacy-screen 🎉
