### ISSUE TITLE
UXCam

### ISSUE THREAD

**Issue by SalahAdDin** [capacitor-community/proposals#86]
## Plugin Request

**Name**: UXCam
**Package**: `@capacitor-community/uxcam`

### Platform(s)

- [x] Android

- [x] iOS

- [x] Web

### Existing Solutions

As **CloudNesil** we have created a new [plugin](https://github.com/SalahAdDin/capacitor-uxcam).
### Description

In order to improve the user's engagement, productivity, etc.; we need to collect data from the users' sessions in order to figure out how improve the UX, usability, etc.
Although it is true that **FirebaseAnalytics** and **Crashlytics** are of valuable utility, these tools do not allow us to see the session of each user in "real" time, making it difficult to analyze their behavior in said application. Fortunately, for this type of analysis we can use Session Recording, and among the tools that provide this feature, **UXCam** is one of the most used.

As **CloudNesil**, we have developed a plugin which integrates **UXCam** into **Capacitor** with support for all platforms and we want to integrate it into the **Capacitor's Community**.

**Comment by imhoffd** [comment]
@SalahAdDin Would you mind joining the [Capacitor Contributor slack](https://getcapacitor.herokuapp.com/)? I can help you get set up with the Capacitor Community and get this plugin integrated. 😄

**Comment by SalahAdDin** [comment]
> @SalahAdDin Would you mind joining the [Capacitor Contributor slack](https://getcapacitor.herokuapp.com/)? I can help you get set up with the Capacitor Community and get this plugin integrated. 😄

Coming then.

**Comment by imhoffd** [comment]
https://github.com/capacitor-community/uxcam 🎉
