### ISSUE TITLE
Microsoft App Center

### ISSUE THREAD

**Issue by johnborges** [capacitor-community/proposals#88]
## Plugin Request

**Name**: appcenter-sdk
**Package**: `@capacitor-community/appcenter-sdk`

### Platform(s)
iOS, Android

### Existing Solutions
https://github.com/microsoft/appcenter-sdk-cordova

### Description
Capacitor enabled SDK for the offerings under MS App Center. Probably shouldn't include Push feature since its being retired.

**Comment by riderx** [comment]
@johnborges i added your plugin to [awesome-capacitor](https://github.com/riderx/awesome-capacitor) if that is useful please take time to star the repo as well :)

**Comment by johnborges** [comment]
project has been created: https://github.com/capacitor-community/appcenter-sdk-capacitor
